
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Samson
  description: Core deployment tool. Developed in house and now open sourced.  The only recommended mechanism for pushing code to production. Deployment configurations are organized by projects, which really act as containers for deployment target configurations.
  links: 
    - url: https://cerebro.zende.sk/projects/samson
      title: Cerebro
    - url: https://zendesk.atlassian.net/wiki/spaces/INFR/pages/96470779/Samson
      title: Project Page
    - url: https://github.com/zendesk/samson
      title: GitHub Repo
      icon: github
  annotations:
    github.com/project-slug: zendesk/samson
    github_repo_url: github.com/repos/zendesk/samson
spec:
  type: service
  lifecycle: production
  owner: group:deploy
