apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
    name: deploy
    description: Manages company deployments
    links: 
        - url: https://cerebro.zende.sk/teams/deploy
          title: Cerebro Link
spec:
    type: team
    profile:
        displayName: Deploy
    parent: engineering-productivity
    children: []