apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: engineering-productivity
  description: Manages company engineers
  links: 
    - url: https://cerebro.zende.sk/teams/eng-productivity
      title: Cerebro Link
spec:
  type: team
  profile:
    displayName: Engineering Productivity
  children: [deploy]
