apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jack-sabinash
  links: 
  - url: https://cerebro.zende.sk/users/jack-sabinash
    title: Cerebro Link
spec:
  memberOf: [deploy]
  profile:
    displayName: Jack Sabinash
    email: jack.sabinash@zendesk.com
